MDValidator/MDValidator.App/Models/FileUploadControlViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MDValidator.App.Models
{
    public class FileUploadControlViewModel
    {
        public FileUploadControlViewModel()
        {
            this.UploadBtnText = "Upload File";
        }

        public FileUploadControlViewModel(string uploadBtnText, string area = "", string controller = "", string action = "")
        {
            this.UploadBtnText = uploadBtnText;
            this.Area = area;
            this.Controller = controller;
            this.Action = action;
        }

        public string UploadBtnText { get; set; }

        public string Area { get; set; }

        public string Controller { get; set; }

        public string Action { get; set; }
    }
}

MDValidator/MDValidator.App/Areas/Configuration/Controllers/ExtractionRulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MDValidator.App.Areas.Configuration.Models.ExtractionRules;
using Microsoft.AspNetCore.Hosting;
using MDValidator.App.Services.Configuration.ExtractionRules;
using MDValidator.App.Utilities;
using MDValidator.Domain.Configuration.ExtractionRules;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net;

namespace MDValidator.App.Areas.Configuration.Controllers
{
    [Area("Configuration")]
    public class ExtractionRulesController : Controller
    {
        private IHostingEnvironment _environment;
        private IExtractionRulesService _extractionRulesSvc;
        private string _extractionHeaderSessionKey = "ExtractionHeader";
        private string _extractionItemsSessionKey = "ExtractionItems";

        public ExtractionRulesController(IHostingEnvironment environment, IExtractionRulesService extractionRulesSvc)
        {
            _environment = environment;
            _extractionRulesSvc = extractionRulesSvc;
        }

        #region HEADER

        public async Task<IActionResult> Header()
        {
            HeadersViewModel vm = new HeadersViewModel();

            var headers = HttpContext.Session.Get<List<Header>>(_extractionHeaderSessionKey);

            if (headers != null)
            {
                vm.Headers = headers;
            }

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Header(ICollection<IFormFile> files)
        {
            HeadersViewModel vm = new HeadersViewModel();

            var uploads = Path.Combine(_environment.WebRootPath, "uploads");

            if (files.Count < 1)
            {
                return View(vm);
            }

            var file = files.First();

            string fileName = Path.Combine(uploads, file.FileName);

            if (file.Length > 0)
            {
                using (var fileStream = new FileStream(fileName, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            //validate file
            vm = _extractionRulesSvc.ProcessHeaderFile(fileName);

            if (vm.Errors.Count > 0)
            {
                HttpContext.Session.Remove(_extractionHeaderSessionKey);
            }
            else
            {
                HttpContext.Session.Set<List<Header>>(_extractionHeaderSessionKey, vm.Headers);
            }

            System.IO.File.Delete(fileName);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SaveHeader()
        {
            var hIds = HttpContext.Session.Get<List<Header>>(_extractionHeaderSessionKey);
            var iIds = HttpContext.Session.Get<List<Item>>(_extractionItemsSessionKey);

            List<string> headerIds = new List<string>();
            List<string> itemIds = new List<string>();

            if (hIds != null)
            {
                headerIds = hIds.Select(h => h.ExtrId).ToList();
            }

            if (iIds != null)
            {
                itemIds = iIds.Select(i => i.ExtrId).ToList();
            }

            bool isConsistent = _extractionRulesSvc.CheckHeaderItemsConsistency(headerIds, itemIds);

            if (!isConsistent)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Data inconsistency between Header and Item tables");
            }

            Response.StatusCode = (int)HttpStatusCode.Created;
            return Json("Ectraction Header saved Successfully");
        }

        #endregion

        #region ITEMS

        public async Task<IActionResult> Items()
        {
            ItemsViewModel vm = new ItemsViewModel();

            var items = HttpContext.Session.Get<List<Item>>(_extractionItemsSessionKey);

            if (items != null)
            {
                vm.Items = items;
            }

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Items(ICollection<IFormFile> files)
        {
            ItemsViewModel vm = new ItemsViewModel();

            var uploads = Path.Combine(_environment.WebRootPath, "uploads");

            if (files.Count < 1)
            {
                return View(vm);
            }

            var file = files.First();

            string fileName = Path.Combine(uploads, file.FileName);

            if (file.Length > 0)
            {
                using (var fileStream = new FileStream(fileName, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            //validate file
            vm = _extractionRulesSvc.ProcessItemsFile(fileName);

            if (vm.Errors.Count > 0)
            {
                HttpContext.Session.Remove(_extractionItemsSessionKey);
            }
            else
            {
                HttpContext.Session.Set<List<Item>>(_extractionItemsSessionKey, vm.Items);
            }

            System.IO.File.Delete(fileName);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SaveItems()
        {
            var hIds = HttpContext.Session.Get<List<Header>>(_extractionHeaderSessionKey);
            var iIds = HttpContext.Session.Get<List<Item>>(_extractionItemsSessionKey);

            List<string> headerIds = new List<string>();
            List<string> itemIds = new List<string>();

            if (hIds != null)
            {
                headerIds = hIds.Select(h => h.ExtrId).ToList();
            }

            if (iIds != null)
            {
                itemIds = iIds.Select(i => i.ExtrId).ToList();
            }

            bool isConsistent = _extractionRulesSvc.CheckHeaderItemsConsistency(headerIds, itemIds);

            if (!isConsistent)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Data inconsistency between Header and Item tables");
            }

            Response.StatusCode = (int)HttpStatusCode.Created;
            return Json("Extraction Items saved Successfully");
        }

        #endregion
    }
}

MDValidator/MDValidator.App/Areas/Configuration/Controllers/ReadingRulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MDValidator.App.Areas.Configuration.Models.ReadingRules;
using Microsoft.AspNetCore.Hosting;
using MDValidator.App.Services.Configuration.ReadingRules;
using MDValidator.App.Utilities;
using MDValidator.Domain.Configuration.ReadingRules;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net;

namespace MDValidator.App.Areas.Configuration.Controllers
{
    [Area("Configuration")]
    public class ReadingRulesController : Controller
    {
        private IHostingEnvironment _environment;
        private IReadingRulesService _readingRulesSvc;
        private string _readingHeaderSessionKey = "ReadingHeader";
        private string _readingItemsSessionKey = "ReadingItems";

        public ReadingRulesController(IHostingEnvironment environment, IReadingRulesService readingRulesSvc)
        {
            _environment = environment;
            _readingRulesSvc = readingRulesSvc;
        }

        #region HEADER

        public async Task<IActionResult> Header()
        {
            HeadersViewModel vm = new HeadersViewModel();

            var headers = HttpContext.Session.Get<List<Header>>(_readingHeaderSessionKey);

            if (headers != null)
            {
                vm.Headers = headers;
            }

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Header(ICollection<IFormFile> files)
        {
            HeadersViewModel vm = new HeadersViewModel();

            var uploads = Path.Combine(_environment.WebRootPath, "uploads");

            if (files.Count < 1)
            {
                return View(vm);
            }

            var file = files.First();

            string fileName = Path.Combine(uploads, file.FileName);

            if (file.Length > 0)
            {
                using (var fileStream = new FileStream(fileName, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            //validate file
            vm = _readingRulesSvc.ProcessHeaderFile(fileName);

            if (vm.Errors.Count > 0)
            {
                HttpContext.Session.Remove(_readingHeaderSessionKey);
            }
            else
            {
                HttpContext.Session.Set<List<Header>>(_readingHeaderSessionKey, vm.Headers);
            }

            System.IO.File.Delete(fileName);

            return View(vm);
        }
        
        [HttpPost]
        public async Task<IActionResult> SaveHeader()
        {
            var hIds = HttpContext.Session.Get<List<Header>>(_readingHeaderSessionKey);
            var iIds = HttpContext.Session.Get<List<Item>>(_readingItemsSessionKey);

            List<string> headerIds = new List<string>();
            List<string> itemIds = new List<string>();

            if (hIds != null)
            {
                headerIds = hIds.Select(h => h.ReadId).ToList();
            }

            if (iIds != null)
            {
                itemIds = iIds.Select(i => i.ReadId).ToList();
            }

            bool isConsistent = _readingRulesSvc.CheckHeaderItemsConsistency(headerIds, itemIds);

            if (!isConsistent)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Data inconsistency between Header and Item tables");
            }

            Response.StatusCode = (int)HttpStatusCode.Created;
            return Json("Validation Header saved Successfully");
        }

        #endregion

        #region ITEMS

        public async Task<IActionResult> Items()
        {
            ItemsViewModel vm = new ItemsViewModel();

            var items = HttpContext.Session.Get<List<Item>>(_readingItemsSessionKey);

            if (items != null)
            {
                vm.Items = items;
            }

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Items(ICollection<IFormFile> files)
        {
            ItemsViewModel vm = new ItemsViewModel();

            var uploads = Path.Combine(_environment.WebRootPath, "uploads");

            if (files.Count < 1)
            {
                return View(vm);
            }

            var file = files.First();

            string fileName = Path.Combine(uploads, file.FileName);

            if (file.Length > 0)
            {
                using (var fileStream = new FileStream(fileName, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            //validate file
            vm = _readingRulesSvc.ProcessItemsFile(fileName);

            if (vm.Errors.Count > 0)
            {
                HttpContext.Session.Remove(_readingItemsSessionKey);
            }
            else
            {
                HttpContext.Session.Set<List<Item>>(_readingItemsSessionKey, vm.Items);
            }

            System.IO.File.Delete(fileName);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SaveItems()
        {
            var hIds = HttpContext.Session.Get<List<Header>>(_readingHeaderSessionKey);
            var iIds = HttpContext.Session.Get<List<Item>>(_readingItemsSessionKey);

            List<string> headerIds = new List<string>();
            List<string> itemIds = new List<string>();

            if (hIds != null)
            {
                headerIds = hIds.Select(h => h.ReadId).ToList();
            }

            if (iIds != null)
            {
                itemIds = iIds.Select(i => i.ReadId).ToList();
            }

            bool isConsistent = _readingRulesSvc.CheckHeaderItemsConsistency(headerIds, itemIds);

            if (!isConsistent)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Data inconsistency between Header and Item tables");
            }

            Response.StatusCode = (int)HttpStatusCode.Created;
            return Json("Reading Items saved successfully");
        }

        #endregion
    }
}

MDValidator/MDValidator.App/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MDValidator.App</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MDValidator.App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - MDValidator.App</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

MDValidator/MDValidator.App/Views/Shared/_ErrorSummary.cshtml
@model List<string>

<div class="errors panel panel-danger">
    <!-- Default panel contents -->
    <div class="panel-heading">Errors</div>
    <div class="panel-body">
        <ul>
            @foreach (var error in Model)
            {
                <li><p>@error</p></li>
            }
        </ul>
    </div>
</div>

MDValidator/MDValidator.App/Views/Shared/_FileUploadControl.cshtml
@using MDValidator.App.Models
@model FileUploadControlViewModel

<div class="fileUploadControl">
    <form class="fileUploadForm" method="post" enctype="multipart/form-data">
        <input type="file" name="files" accept="xls, xslx" />
        @*<input type="submit" value="Upload Official List File" class="btn btn-primary"/>*@
    </form>
    <button class="btn btn-primary btnSelectFile"><i class="fa fa-upload fa-fw"></i> @Model.UploadBtnText</button>
</div>&nbsp;&nbsp;

MDValidator/MDValidator.App/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MDValidator.App</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/metisMenu/dist/metisMenu.min.css" />
        <link rel="stylesheet" href="~/lib/sweetalert/dist/sweetalert.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/metisMenu/dist/metisMenu.min.css" />
        <link rel="stylesheet" href="~/lib/sweetalert/dist/sweetalert.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>

    <div class="wrapper">
        @*NAVIGATION*@
        <nav class="navbar navbar-default navbar-primary navbar-fixed-top" role="navigation" style="margin-bottom: 0;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">MD Validator</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        
                        <li>
                            <a asp-area="Validation" asp-controller="OfficialList" asp-action="Index"><i class="fa fa-check-square-o fa-fw"></i> Validation</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> Configuration<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a asp-area="Configuration" asp-controller="LaneMaster" asp-action="Index">Lane Master file</a>
                                </li>
                                <li>
                                    <a href="#">Validation Rules <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a asp-area="Configuration" asp-controller="ValidationRules" asp-action="Header">Header</a>
                                        </li>
                                        <li>
                                            <a asp-area="Configuration" asp-controller="ValidationRules" asp-action="Items">Items</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                <li>
                                    <a href="#">Reading Rules <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a asp-area="Configuration" asp-controller="ReadingRules" asp-action="Header">Header</a>
                                        </li>
                                        <li>
                                            <a asp-area="Configuration" asp-controller="ReadingRules" asp-action="Items">Items</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                                <li>
                                    <a href="#">Estraction Rules <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a asp-area="Configuration" asp-controller="ExtractionRules" asp-action="Header">Header</a>
                                        </li>
                                        <li>
                                            <a asp-area="Configuration" asp-controller="ExtractionRules" asp-action="Items">Items</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-users fa-fw"></i> Management<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="blank.html">Roles</a>
                                </li>
                                <li>
                                    <a href="login.html">Users</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->

        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">@ViewData["Title"]</h2>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            @RenderBody()
        </div>
    </div>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/metisMenu/dist/metisMenu.min.js"></script>
        <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/metisMenu/dist/metisMenu.min.js"></script>
        <script src="~/lib/sweetalert/dist/sweetalert.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>